// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ProductAPI.Migrations
{
    [DbContext(typeof(SqlDbContext))]
    [Migration("20241103085416_migration1")]
    partial class migration1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductLib.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar")
                        .HasColumnName("Id");

                    b.Property<byte>("Category")
                        .HasColumnType("tinyint")
                        .HasColumnName("Category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Code");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime")
                        .HasColumnName("Created");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime")
                        .HasColumnName("LastUpdated");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "82124f5a-2f0a-438e-82e9-3aa735cd9367",
                            Category = (byte)1,
                            Code = "PRD001",
                            Created = new DateTime(2024, 11, 3, 15, 54, 16, 457, DateTimeKind.Local).AddTicks(9887),
                            Name = "Coca"
                        },
                        new
                        {
                            Id = "cc92d39e-2de5-4b00-8c54-83dffb2362dc",
                            Category = (byte)32,
                            Code = "PRD002",
                            Created = new DateTime(2024, 11, 3, 15, 54, 16, 457, DateTimeKind.Local).AddTicks(9903),
                            Name = "Dream 125"
                        },
                        new
                        {
                            Id = "08802dba-e7db-4084-81a8-e58d5db624c3",
                            Category = (byte)4,
                            Code = "PRD003",
                            Created = new DateTime(2024, 11, 3, 15, 54, 16, 457, DateTimeKind.Local).AddTicks(9906),
                            Name = "TShirt-SEA game 2023"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
